version: '3.6'

services:
  smartbrain-api:
    container_name: backend
    build: ./
    command: yarn start
    working_dir: /home/r1oga/dev/udemy/junior-to-senior/smartbrain/api
    environment:
      POSTGRES_URI: postgres://joe:biden@postgres:5432/smartbrain-docker
      POSTGRES_USER: joe
      POSTGRES_PASSWORD: biden
      POSTGRES_DB: smartbrain-docker
      POSTGRES_HOST: postgres
      REDIS_URI: redis://redis:6379
      JWT_SECRET: 'lolol'
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/r1oga/dev/udemy/junior-to-senior/smartbrain/api

  postgres:
    environment:
      POSTGRES_USER: joe
      POSTGRES_PASSWORD: biden
      POSTGRES_DB: smartbrain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - '5433:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
